# Generated by Django 4.2.5 on 2023-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Service_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, default=None, max_length=2500, null=True)),
                ('Short_Description', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Service_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('Description', models.CharField(blank=True, default=None, max_length=2500, null=True)),
                ('Short_Description', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
