# Generated by Django 4.2.5 on 2023-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_systems_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='web_ink',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='web_ink',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
