# Generated by Django 4.2.5 on 2023-09-23 20:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IMS_systems_web', '0003_fueluser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelUser',
            new_name='Users',
        ),
    ]
