# Generated by Django 4.2.5 on 2023-09-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_systems_web', '0004_rename_fueluser_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Service_name',
            new_name='Product_name',
        ),
    ]
